name: 'SFTP Deploy'
description: 'Securely deploy files to a remote server via SFTP using SSH key authentication'
author: 'Brandom Vasquez'

branding:
  icon: 'upload-cloud'  # From Feather Icons set
  color: 'blue'

inputs:
  host:
    description: 'SFTP host'
    required: true
  username:
    description: 'SFTP username'
    required: true
  private-key:
    description: 'SSH private key'
    required: true
  port:
    description: 'SFTP port'
    required: false
    default: '22'
  source-dir:
    description: 'Local directory to upload'
    required: false
    default: './dist'
  remote-dir:
    description: 'Remote directory on the server'
    required: false
    default: '/var/www/html'

outputs:
  deployed-files:
    description: 'Number of files deployed'
  deployment-time:
    description: 'Timestamp of deployment completion'

runs:
  using: 'node20'
  main: 'src/deploy.js'